### PR TITLE
Add ability to get service endpoint names

### PR DESCRIPTION
**Pull request by Willyham**
@kriskowal

### CODE REVIEW

**Comment by Raynos** [comment]
lgtm.

**Comment by kriskowal** [comment]
lgtm.

**Comment by Willyham** [comment]
@kriskowal Can you build a release for thriftrw? I seem to remember this is a fairly stringent process for it and I'm not sure what other changes have been made.

**Comment by kriskowal** [comment]
Thanks, I’ll take care of it.

**Pull request merged**
